##read config file will read data from this file

[admin login info]
admin_page_url = https://stagingiassess2.myamcat.com/
username = priya.Sharma@yopmail.com
password = VZ6n@tTStuHnBZV
invalid_password = admin12123